/**
 * Wild Workouts trainer
 * TODO
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HourUpdate model module.
 * @module model/HourUpdate
 * @version 1.0.0
 */
class HourUpdate {
    /**
     * Constructs a new <code>HourUpdate</code>.
     * @alias module:model/HourUpdate
     * @param hours {Array.<Date>} 
     * @param topic {Array.<String>} 
     * @param tags {Array.<String>} 
     */
    constructor(hours, topic, tags) { 
        
        HourUpdate.initialize(this, hours, topic, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hours, topic, tags) { 
        obj['hours'] = hours;
        obj['topic'] = topic;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>HourUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HourUpdate} obj Optional instance to populate.
     * @return {module:model/HourUpdate} The populated <code>HourUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HourUpdate();

            if (data.hasOwnProperty('hours')) {
                obj['hours'] = ApiClient.convertToType(data['hours'], ['Date']);
            }
            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], ['String']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Date>} hours
 */
HourUpdate.prototype['hours'] = undefined;

/**
 * @member {Array.<String>} topic
 */
HourUpdate.prototype['topic'] = undefined;

/**
 * @member {Array.<String>} tags
 */
HourUpdate.prototype['tags'] = undefined;






export default HourUpdate;

